name = "rustpack"
output = "rustpack.rpack"
#targets = [
#    "x86_64-unknown-linux-gnu",
#    "x86_64-apple-darwin",
#    "x86_64-pc-windows-msvc",
#    "aarch64-apple-darwin"
#]
strip = true
compress = true
lto = "thin"
profile = "release"
no_default_features = false
#features = [
#    "feature1", 
#    "feature2", 
#    "advanced-logging"
#]

#assets = [
#  "assets/"
#]
zip = false
watch = false
verbose = true
#sign = "your-secret-key-here"